### ISSUE TITLE
How to create training_solutions_rev1.csv for the downloaded dataset

### ISSUE THREAD

**Issue by hariharan-devarajan** [pegasus-isi/galaxy-classification-wf#1]
Based on the instructions i have downloaded the complete dataset from the kaggle website. However, the create dataset assumes the presence of a csv. How do I create that said csv. It would be useful to add the information (maybe a script as well) on the readme.

**Comment by papajim** [comment]
Hi Hari,

I would start with the works21 branch. It's cleaner than the master.
The csv you are asking about is under the config folder, no need to generate it.
